# Generated by Django 5.1.6 on 2025-02-21 07:25

import app00Administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firm_id', models.CharField(default=app00Administration.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=200)),
                ('firm_domain', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
